# Generated by Django 4.2.19 on 2025-03-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='capacidad',
            field=models.FloatField(),
        ),
    ]
