# Generated by Django 5.1.7 on 2025-03-08 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gastocamion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SueldoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('adelanto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque')], default='efectivo', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sueldos', to='core.conductor')),
            ],
        ),
    ]
