# Generated by Django 5.1.7 on 2025-03-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sueldoempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sueldoempleado',
            name='periodo_sueldo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sueldoempleado',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque')], default='transferencia', max_length=20),
        ),
    ]
