# Generated by Django 5.1.7 on 2025-03-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('horas_espera', models.FloatField()),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peajes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe_lista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='core.cliente')),
            ],
        ),
    ]
